## AUTOGRAD



In [2]:
import torch

In [3]:
x = torch.ones(2, 2, requires_grad = True)
x
# Create a tensor and set requires_grad=True to track computation with it

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [5]:
y.grad_fn

In [6]:
z = y * y * 3
out = z.mean()
z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [14]:
a = torch.randn(2, 2)
print(a)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(a)
print(a * a)
print(b)
b.grad_fn

tensor([[ 0.4077,  0.3624],
        [-0.1338, -0.4660]])
False
True
tensor([[-2.0650, -1.7049],
        [ 0.3539,  0.9536]], requires_grad=True)
tensor([[4.2643, 2.9067],
        [0.1253, 0.9094]], grad_fn=<MulBackward0>)
tensor(8.2057, grad_fn=<SumBackward0>)


### Gradients 
反向传播
out  包括一个scalar
out.backward() 相当于   out.backward(torch.tensor(1.))

In [9]:
out.backward()

In [15]:
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [16]:
x = torch.randn(3, requires_grad = True)

y = x*2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([405.9031, 786.7767, 791.7477], grad_fn=<MulBackward0>)


In [17]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [18]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
